# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1569272bb81861622b0cfeb8a711c97e76a56ab7128e28f6751bbf1013dde32ab9ca12519077d79c679bcfd7772ea0b971418a0c21ec461be13a52248bb499e3

test:
  secret_key_base: 5d4b6b3552351114aa52c1ea201d35236ef655ef885280839e246031c8109510bc2997b9b17fc3f22c731549112e9714b88d90b33641fc50ff9c2895ea825f2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
